name: Bug Report
description: Report a bug or unexpected behavior in the mod
title: "[BUG] <short description>"
labels: [bug]
body:
  - type: input
    id: game_version
    attributes:
      label: Game Version
      description: What version of the game are you using?
      placeholder: e.g., 1.20.10, 1.20.7, etc.
    validations:
      required: true

  - type: textarea
    id: other_mods
    attributes:
      label: Other Mods Used
      description: List all other mods you are using with this one.
      placeholder: |
        - MoreMapIcons
        - Cartographer
        - etc.
    validations:
      required: false

  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: Detailed Steps to Reproduce
      description: Describe the issue in detail. What were you doing when the bug occurred? Include clear steps to reproduce.
      placeholder: |
        1. Opening map
        2. Interact with search bar
        3. etc.
    validations:
      required: true

